### ISSUE TITLE
Pesquisar em artigos científicos sobre projetos de educação comunitária online

### ISSUE THREAD

**Issue by devevila** [ProjetoEvila/evl_extensao#12]

**Comment by cadullira** [comment]
**Artigos selecionados:**

[Democratizando as relações pela conquista da cidadania: O trabalho da educação comunitária ](http://revista.fumec.br/index.php/paideia/article/view/9579)

[ Educação Social: desafios e contribuições no enfrentamento da vulnerabilidade e desigualdade social ](https://periodicos.ufms.br/index.php/EIGEDIN/article/view/14146)

**Comment by cadullira** [comment]
Artigos fazem a abordagem sobre a questão do tema Educação Comunitária, porém nada sobre o termo "online". Na pesquisa não foi encontrado nenhum artigo que realizasse essa exposição.

- [ ] Fazer relatório da leitura

**Comment by prof-francisco-ferreira** [comment]
Analisa se esses artigos são relevantes. Foca no método, não exatamente na forma igual a que tu tá pretendendo fazer.
https://doi.org/10.5212/praxeduc.v.18.21337.011 
http://dx.doi.org/10.36298/gerais2020130108 
http://www.bdtd.uerj.br/handle/1/17426
https://d1wqtxts1xzle7.cloudfront.net/88222299/pdf-libre.pdf?1656957304=&response-content-disposition=inline%3B+filename%3DVideos_Educativos_em_Aleitamento_Materno.pdf&Expires=1713475848&Signature=ZgINw80yzpK60g~xfek5F5qm5T2bM~PHYm8WlwjNaIJw4HM5J~eFQOO0PkWA9iWcwmG9u7KWlea5eTA7BXbW7s6Bo6EeLOu0fdu-792KXpyy~xTKrZrATSqDOzTIWD9Q7kKrsgKCdihU24HzHf4JQSIOIduH0ey-I23pnkOGjr0G9Q1roYfhvovttfY-cYQf574Mg~dgGROGYsPU2e7HoLVtiGTfVuhmLTam-5je8XnyCkEGNTf5WOjAuUnRizLYnqHaxRVQXnERdM-IxTGWYGObrO9hSF4zQshHaHv3hNKNFeLH--NnBSB9xIulXXtr1kIYpz8PO-IqoUhZI047-A__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA
