### ISSUE TITLE
Investigar bug chamillo

### ISSUE THREAD

**Issue by prof-francisco-ferreira** [ProjetoEvila/evl_extensao#22]
https://evila.site/labchamilo/

Deprecated: Return type of System\Session::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/u606662901/domains/evila.site/public_html/labchamilo/main/inc/lib/system/session.class.php on line 125

Deprecated: Return type of System\Session::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/u606662901/domains/evila.site/public_html/labchamilo/main/inc/lib/system/session.class.php on line 138

Deprecated: Return type of System\Session::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/u606662901/domains/evila.site/public_html/labchamilo/main/inc/lib/system/session.class.php on line 143

Deprecated: Return type of System\Session::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/u606662901/domains/evila.site/public_html/labchamilo/main/inc/lib/system/session.class.php on line 148

**Comment by cadullira** [comment]
Erro com relação a versão do PHP. Atualmente o PHP roda sua versão 8.3, porém o Chamilo que usa o PHP na sua construção roda com a versão 7.4. Na implementação pede que o retorno da Session sejam compatíveis com a interface ArrayAccess.
