### ISSUE TITLE
Confeccionar slide de apresentação do projeto

### ISSUE THREAD

**Issue by devevila** [ProjetoEvila/evl_extensao#3]

**Comment by cadullira** [comment]
Slides base criado, falta fazer o "refinamento"

**Comment by cadullira** [comment]
Na reunião semanal #5, ficou decidido que os slides serão desenvolvidos no LibreOffice Impress. Todo o projeto estará na minha máquina, e versionado via git, e armazenado remotemente no GitHub.

**Comment by cadullira** [comment]
Slide de apresentação do projeto atualmente finalizado.
