### ISSUE TITLE
Reunião Semanal 08-03

### ISSUE THREAD

**Issue by devevila** [ProjetoEvila/evl_extensao#6]
- preencher formulário de acompanhamento: https://forms.gle/6j64vmc3nzAtqmfq5
- adicionar tópicos abordados
- registrar presença com imagem

**Comment by cadullira** [comment]
- Github - prof-francisco-ferreira
- Criar projeto do github 

- Ações necessárias

> -  Refinar os slides
> - Documentar esse estudo de requisitos. 



![Image](https://github.com/ProjetoEvila/evl_extensao/assets/110053719/2d8e0aab-9ce9-4f7d-a269-e41b95ca0a71)

**Comment by cadullira** [comment]
Github - prof-francisco-ferreira
Criar projeto do github 

Ações necessárias

- Refinar os slides
- Documentar esse estudo de requisitos. 



![Image](https://github.com/ProjetoEvila/evl_extensao/assets/110053719/5b88960d-bcd0-4210-a8d1-cdd515fab926)
